import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';

export default function ImpactAreas() {
	return (
		<div>
			<Head>
				<title>Inclusion Labs</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Header />

			<main className={styles.main}>
				<h1 className={styles.title}>Choose an impact area</h1>

				<div className={styles.grid}>
					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>

					<div className={styles.card}>
						<h2>Impact area</h2>
						<p>Score:</p>
					</div>
				</div>
			</main>
		</div>
	);
}
