import Head from 'next/head';

export default function ImpactAreas() {
	return (
		<div>
			<Head>
				<title>Inclusion Labs</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
		</div>
	);
}
